export const CREATE_EVENT = "CREATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const DELETE_ALL_EVENTS = "DELETE_ALL_EVENTS";

export const ADD_ORERATION_LOG = "ADD_ORERATION_LOG";
export const DELETE_ALL_ORERATION_LOGS = "DELETE_ALL_ORERATION_LOGS";

        